repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.0.9 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
